styleguide: odineiramone/linters
engines:
  reek:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    config:
      languages:
      - ruby
    enabled: true
  remark-lint:
    enabled: true
  bundler-audit:
    enabled: true
exclude_paths:
- bin
- config
- db
- public
- script
- spec
- test
- vendor
